SelectMission("m1")

SetMissionResetPlayerOutCar("level1_homer_start","level1_carstart")
SetDynaLoadData("l1z1.p3d;l1r1.p3d;l1r7.p3d;")
SetAnimatedCameraName( "cameraShape1" )
SetAnimCamMulticontName( "MasterController" )

UsePedGroup( 0 ) 

AddStage(0)
	RESET_TO_HERE()
	SetHUDIcon( "digest" )
	SetStageMessageIndex(179)
	AddObjective( "goto" )
		SetDestination("m1_AI_path1", "carsphere")
		SetStageTime(90)
	CloseObjective()
	ShowStageComplete()
CloseStage()

AddStage(1)
	SetHUDIcon( "digest" )
	SetStageMessageIndex(187)
	AddObjective( "goto" )
		SetDestination("m1_AI_path4", "carsphere")
		SetStageTime(65)
	CloseObjective()
	ShowStageComplete()
CloseStage()

AddStage(2)
	SetStageMessageIndex(153)
	SetHUDIcon( "digest" )
	AddObjective( "goto" )
		TurnGotoDialogOff()
		SetDestination("m1_tomato","scien")
		SetStageTime(90)
	CloseObjective()
	ShowStageComplete()
CloseStage()

AddStage(3)
	SetHUDIcon ( "school" )
	SetStageTime(120)
	AddObjective( "goto" )
		SetDestination("SpringfieldElementary", "carsphere")
	CloseObjective()
CloseStage()

AddStage(4)
	SetStageMessageIndex(1)
	SetHUDIcon( "school" )
	SetMaxTraffic(2)
	SetStageMusicAlwaysOn()
	AddObjective("interior", "nearest road")
		SetDestination("SpringfieldElementary", "school_mission_doorstar")
	CloseObjective()
CloseStage()


AddStage(5)
	SetStageMessageIndex(156)
	SetHUDIcon( "lisa" )
	SetMaxTraffic(2)
	SetStageMusicAlwaysOn()
	AddObjective("talkto", "nearest road")
		AddNPC("lisa","m1_lisa_place")
		AddObjectiveNPCWaypoint( "lisa", "lisa_walk_1" )
		AddObjectiveNPCWaypoint( "lisa", "lisa_walk_2" )
		AddObjectiveNPCWaypoint( "lisa", "lisa_walk_1" )
		SetTalkToTarget("lisa",0, -0.5)
	CloseObjective()
CloseStage()

AddStage("final")
	AddObjective("dialogue")
		AmbientAnimationRandomize( 1, 0 )
		AmbientAnimationRandomize( 0, 0 )
		AddAmbientNpcAnimation( "dialogue_yes" )
		AddAmbientNpcAnimation( "none" )
		AddAmbientNpcAnimation( "dialogue_hands_on_hips" )
		AddAmbientNpcAnimation( "none" )
		AddAmbientNpcAnimation( "dialogue_yes" )
		AddAmbientNpcAnimation( "none" )
		AddAmbientPcAnimation( "none" )
		AddAmbientPcAnimation( "dialogue_scratch_head" )
		AddAmbientPcAnimation( "none" )
		AddAmbientPcAnimation( "dialogue_no" )
		AddAmbientPcAnimation( "none" )
		AddAmbientPcAnimation( "dialogue_yes" )
		SetDialogueInfo("homer","lisa","bladder",0)
	CloseObjective()
CloseStage()

CloseMission()