SelectMission("m2sd")

SetMissionResetPlayerOutCar("level1_homer_start", "level1_carstart")
SetDynaLoadData("l1z1.p3d;l1r1.p3d;l1r7.p3d;")

UsePedGroup( 0 ) 

AddStage(0)
	AddObjective("goto")
		SetDestination("m2_simpsonhouse_sd")
		AddNPC("marge", "m1_marge_sd")
	CloseObjective()
CloseStage()

AddStage(1)
	RESET_TO_HERE()
	SetHUDIcon("marage")
	SetStageMessageIndex(04)
	AddObjective("timer")
		SetDurationTime(3)
	CloseObjective()
CloseStage()

AddStage(2)
	SetHUDIcon("homer")
	SetStageMessageIndex(03)
	AddObjective("timer")
		SetDurationTime(3)
	CloseObjective()
CloseStage()

AddStage(3)
	SetHUDIcon("marage")
	SetStageMessageIndex(17)
	AddObjective("timer")
		SetDurationTime(3)
	CloseObjective()
CloseStage()

AddStage(4)
	SetHUDIcon("marage")
	SetStageMessageIndex(52)
	AddObjective("timer")
		SetDurationTime(3)
	CloseObjective()
CloseStage()

AddStage("final")
	SetStageMessageIndex(02)
	AddObjective("getin")
	SetPresentationBitmap( "art/frontend/dynaload/images/mis01_02.p3d" )
		SetObjTargetVehicle("current")
	CloseObjective()
CloseStage()

CloseMission()